---
- name: Download WordPress
  get_url: 
    url=https://wordpress.org/wordpress-5.2.2.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache
- name: Set the correct permissions on Wordpress directories
  command: find /var/www/wordpress/ -type d -exec chmod 755 {} \;
- name: Set the correct permissions for Wordpress files
  command: find /var/www/wordpress/ -type f -exec chmod 644 {} \;
- name: Copy wp-config
  copy:
    src: wp-config.php
    dest: "/var/www/wordpress/"
  become: yes
